name: But Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:    
  - type: input
    id: mary-version
    attributes:
      label: MaryUI version
      description: You can see number on your `composer.json` file.
      placeholder: "example: 2.7.0"
    validations:
      required: true
      
  - type: input
    id: daisy-version
    attributes:
      label: daisyUI version
      description: You can see number on your `package.json` file.
      placeholder: "example: 2.7.0"
    validations:
      required: true
      
  - type: input
    id: livewire-version
    attributes:
      label: Livewire version
      description: You can see number on your `composer.json` file.
      placeholder: "example: 2.7.0"
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are affected?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge 

  - type: checkboxes
    id: terms
    attributes:
      label: I have pasted code as text
      options:
        - label: I have not pasted code as screenshot
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "Please, dont paste code screenshot, paste code as text!"
    validations:
      required: true
